CREATE TABLE IF NOT EXISTS tz_group_decision_application (
  id CHAR(36) NOT NULL COMMENT '集团决策申请主键UUID',
  application_no VARCHAR(32) NOT NULL COMMENT '集团决策申请单号，格式JTJC-年月-四位序号',
  applicant_user_id VARCHAR(64) NOT NULL COMMENT '申请人用户ID，对应当前经办人账号',
  applicant_name VARCHAR(128) NOT NULL COMMENT '申请人姓名，对应前端申请人',
  applicant_unit_id VARCHAR(64) NULL COMMENT '申请单位组织ID，对应当前经办人所属单位',
  applicant_unit_name VARCHAR(255) NULL COMMENT '申请单位名称，对应前端申请单位',
  application_date DATE NOT NULL COMMENT '申请日期，对应前端申请日期',
  application_year SMALLINT UNSIGNED NOT NULL COMMENT '申请年度，取值范围2000至2100',
  applicant_department_id VARCHAR(64) NULL COMMENT '申请部门组织ID，对应当前经办人所属部门',
  applicant_department_name VARCHAR(255) NULL COMMENT '申请部门名称，对应前端申请部门',
  project_name VARCHAR(255) NULL COMMENT '项目名称，对应前端项目信息项目名称',
  project_code VARCHAR(64) NULL COMMENT '项目编码，对应投资项目唯一业务编码',
  project_leader_user_id VARCHAR(64) NULL COMMENT '项目负责人用户ID',
  project_leader_name VARCHAR(128) NULL COMMENT '项目负责人姓名，对应前端项目负责人',
  planned_start_date DATE NULL COMMENT '计划开始日期',
  planned_end_date DATE NULL COMMENT '计划结束日期',
  investment_entity_id VARCHAR(64) NULL COMMENT '投资主体组织ID',
  investment_entity_name VARCHAR(255) NULL COMMENT '投资主体名称，对应前端投资主体',
  investment_direction VARCHAR(64) NULL COMMENT '投资方向编码，STRATEGIC战略性、FINANCIAL财务性、INDUSTRIAL产业协同',
  domestic_overseas VARCHAR(32) NULL COMMENT '境内外编码，DOMESTIC境内、OVERSEAS境外',
  investment_method VARCHAR(64) NULL COMMENT '投资方式编码，EQUITY股权、FIXED_ASSET固定资产、FUND基金、OTHER其他',
  is_major_project TINYINT(1) NULL COMMENT '是否重大项目，1是、0否',
  currency_code VARCHAR(8) NULL COMMENT '投资币种ISO代码，例如CNY人民币、USD美元',
  project_total_investment DECIMAL(20,2) NULL COMMENT '项目总投资金额，单位元',
  planned_investment DECIMAL(20,2) NULL COMMENT '计划投资金额，单位元',
  expected_return_rate DECIMAL(8,4) NULL COMMENT '预计收益率，单位百分比，取值0至100',
  funding_company_owned DECIMAL(20,2) NULL COMMENT '资金计划中项目公司自有资金，单位元',
  funding_group_requested DECIMAL(20,2) NULL COMMENT '资金计划中申请集团资金，单位元',
  funding_special_bond DECIMAL(20,2) NULL COMMENT '资金计划中项目专项债资金，单位元',
  funding_government DECIMAL(20,2) NULL COMMENT '资金计划中政府资金，单位元',
  funding_loan DECIMAL(20,2) NULL COMMENT '资金计划中贷款资金，单位元',
  funding_other DECIMAL(20,2) NULL COMMENT '资金计划中其他资金，单位元',
  annual_planned_investment DECIMAL(20,2) NULL COMMENT '本年计划投资金额，单位元',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_SEND' COMMENT '单据状态，PENDING_SEND待发、IN_REVIEW审核中、APPROVED已通过、RETURNED已退回',
  current_stage TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前审批节点，0经办人、1经办部门负责人、2经办部门分管领导、3审批完成',
  version BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号，每次修改或流转递增',
  created_by VARCHAR(64) NOT NULL COMMENT '创建人用户ID',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  updated_by VARCHAR(64) NOT NULL COMMENT '最后更新人用户ID',
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_tz_group_decision_application_no (application_no),
  KEY idx_tz_group_decision_status (status, current_stage),
  KEY idx_tz_group_decision_applicant (applicant_user_id, created_at),
  KEY idx_tz_group_decision_project_code (project_code),
  CONSTRAINT chk_tz_group_decision_application_year CHECK (application_year BETWEEN 2000 AND 2100),
  CONSTRAINT chk_tz_group_decision_expected_return CHECK (expected_return_rate IS NULL OR expected_return_rate BETWEEN 0 AND 100),
  CONSTRAINT chk_tz_group_decision_project_total CHECK (project_total_investment IS NULL OR project_total_investment >= 0),
  CONSTRAINT chk_tz_group_decision_planned_investment CHECK (planned_investment IS NULL OR planned_investment >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='集团决策申请主表，投资决策第一步业务单据';

CREATE TABLE IF NOT EXISTS tz_document_workflow_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '单据审批流转记录主键ID',
  document_type VARCHAR(64) NOT NULL COMMENT '单据类型编码，例如GROUP_DECISION_APPLICATION集团决策申请',
  business_id CHAR(36) NOT NULL COMMENT '业务单据主键UUID',
  action VARCHAR(32) NOT NULL COMMENT '审批操作，SUBMIT发送、APPROVE同意、RETURN退回',
  from_stage TINYINT UNSIGNED NOT NULL COMMENT '操作前审批节点编号',
  to_stage TINYINT UNSIGNED NOT NULL COMMENT '操作后审批节点编号',
  operator_id VARCHAR(64) NOT NULL COMMENT '办理人用户ID',
  operator_name VARCHAR(128) NOT NULL COMMENT '办理人姓名',
  operator_role VARCHAR(64) NOT NULL COMMENT '办理人角色，initiator经办人、department_head经办部门负责人、division_leader经办部门分管领导',
  comment VARCHAR(2000) NULL COMMENT '审批意见，最长2000字符',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '审批操作时间',
  PRIMARY KEY (id),
  KEY idx_tz_document_workflow_business (document_type, business_id, created_at),
  KEY idx_tz_document_workflow_operator (operator_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='全局单据审批流转历史表';

CREATE TABLE IF NOT EXISTS tz_document_monthly_sequence (
  document_type VARCHAR(64) NOT NULL COMMENT '单据类型编码，例如GROUP_DECISION_APPLICATION集团决策申请',
  period CHAR(7) NOT NULL COMMENT '编号年月，格式YYYY-MM',
  current_value BIGINT UNSIGNED NOT NULL COMMENT '当前已使用的月度流水号',
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '流水号最后更新时间',
  PRIMARY KEY (document_type, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='各类业务单据月度编号流水表';
