<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { apiRequest } from '../../api';
import { hasPermission } from '../../auth';
import type { DepartmentItem, DirectoryUser, Paged, UnitItem } from '../../types';

const items = ref<DepartmentItem[]>([]); const units = ref<UnitItem[]>([]); const heads = ref<DirectoryUser[]>([]); const leaders = ref<DirectoryUser[]>([]); const error = ref(''); const busy = ref(false);
const empty = () => ({ id: '', unitId: '', code: '', name: '', departmentHeadUserId: '', supervisingLeaderUserId: '', status: 'ACTIVE', sortOrder: 0, version: 0 });
const form = reactive(empty());
const filterUnitId = ref('');
const displayedItems = computed(() => filterUnitId.value ? items.value.filter(item => item.unitId === filterUnitId.value) : items.value);
const headCandidates = computed(() => heads.value.filter(user => user.departmentId === form.id));
const leaderCandidates = computed(() => leaders.value.filter(user => user.unitId === form.unitId));
async function load() { try { const canManage = hasPermission('admin.department.manage'); const [departments, unitList, headList, leaderList] = await Promise.all([apiRequest<Paged<DepartmentItem>>('/admin/departments?pageSize=100'), apiRequest<Paged<UnitItem>>('/admin/units?status=ACTIVE&pageSize=100'), canManage ? apiRequest<DirectoryUser[]>('/directory/users?permission=investment.intention.approve_department') : Promise.resolve([]), canManage ? apiRequest<DirectoryUser[]>('/directory/users?permission=investment.intention.approve_supervising') : Promise.resolve([])]); items.value = departments.items; units.value = unitList.items; heads.value = headList; leaders.value = leaderList; } catch (e) { error.value = e instanceof Error ? e.message : '加载失败'; } }
function reset() { Object.assign(form, empty()); }
function edit(item: DepartmentItem) { Object.assign(form, { ...item, departmentHeadUserId: item.departmentHeadUserId ?? '', supervisingLeaderUserId: item.supervisingLeaderUserId ?? '' }); }
async function save() { busy.value = true; error.value = ''; try { const body = { unitId: form.unitId, code: form.code, name: form.name, departmentHeadUserId: form.id ? form.departmentHeadUserId || null : null, supervisingLeaderUserId: form.id ? form.supervisingLeaderUserId || null : null, status: form.status, sortOrder: form.sortOrder, ...(form.id ? { version: form.version } : {}) }; await apiRequest(form.id ? `/admin/departments/${form.id}` : '/admin/departments', { method: form.id ? 'PUT' : 'POST', body: JSON.stringify(body) }); reset(); await load(); } catch (e) { error.value = e instanceof Error ? e.message : '保存失败'; } finally { busy.value = false; } }
async function remove(item: DepartmentItem) { if (!confirm(`确认删除部门“${item.name}”？`)) return; try { await apiRequest(`/admin/departments/${item.id}`, { method: 'DELETE' }); await load(); } catch (e) { error.value = e instanceof Error ? e.message : '删除失败'; } }
onMounted(load);
</script>
<template><section class="page-card"><div class="page-heading"><div><h1>部门管理</h1><p>部门在单位内平级；创建人员后可回到此处配置负责人。</p></div><button v-if="hasPermission('admin.department.manage')" @click="reset">新建部门</button></div><div class="filter-toolbar"><label>单位筛选<select v-model="filterUnitId"><option value="">全部单位</option><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.name }}</option></select></label></div><div v-if="error" class="form-error">{{ error }}</div><div class="admin-layout"><table class="data-table"><thead><tr><th>单位</th><th>部门编码</th><th>部门名称</th><th>部门负责人</th><th>分管领导</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in displayedItems" :key="item.id"><td>{{ item.unitName }}</td><td>{{ item.code }}</td><td>{{ item.name }}</td><td>{{ item.departmentHeadName || '未配置' }}</td><td>{{ item.supervisingLeaderName || '未配置' }}</td><td>{{ item.status === 'ACTIVE' ? '启用' : '停用' }}</td><td><button class="link-button" @click="edit(item)">编辑</button><button v-if="hasPermission('admin.department.manage')" class="link-button danger-text" @click="remove(item)">删除</button></td></tr></tbody></table><form v-if="hasPermission('admin.department.manage')" class="admin-form side-form" @submit.prevent="save"><h2>{{ form.id ? '编辑部门' : '新建部门' }}</h2><label>所属单位<select v-model="form.unitId" required><option value="">请选择</option><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.name }}</option></select></label><label>部门编码<input v-model="form.code" required maxlength="64"></label><label>部门名称<input v-model="form.name" required maxlength="200"></label><template v-if="form.id"><label>部门负责人<select v-model="form.departmentHeadUserId"><option value="">未配置</option><option v-for="user in headCandidates" :key="user.id" :value="user.id">{{ user.name }}</option></select></label><label>分管领导<select v-model="form.supervisingLeaderUserId"><option value="">未配置</option><option v-for="user in leaderCandidates" :key="user.id" :value="user.id">{{ user.name }}（{{ user.departmentName }}）</option></select></label></template><small v-else>保存部门后，先创建人员并授予审批角色，再配置负责人。</small><label>状态<select v-model="form.status"><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label><label>排序号<input v-model.number="form.sortOrder" type="number" min="0"></label><div class="form-actions"><button type="button" @click="reset">取消</button><button class="primary" :disabled="busy">保存</button></div></form></div></section></template>
