<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { apiRequest } from '../../api';
import { hasPermission } from '../../auth';
import type { DepartmentItem, Paged, PositionItem, UnitItem } from '../../types';
const items = ref<PositionItem[]>([]); const units = ref<UnitItem[]>([]); const departments = ref<DepartmentItem[]>([]); const error = ref(''); const busy = ref(false);
const empty = () => ({ id: '', unitId: '', departmentId: '', code: '', name: '', status: 'ACTIVE', sortOrder: 0, version: 0 }); const form = reactive(empty());
const availableDepartments = computed(() => departments.value.filter(item => item.unitId === form.unitId));
const filterUnitId = ref(''); const filterDepartmentId = ref('');
const filterDepartments = computed(() => departments.value.filter(item => !filterUnitId.value || item.unitId === filterUnitId.value));
const displayedItems = computed(() => items.value.filter(item =>
  (!filterUnitId.value || item.unitId === filterUnitId.value) &&
  (!filterDepartmentId.value || item.departmentId === filterDepartmentId.value)
));
async function load() { try { const [positionList, unitList, departmentList] = await Promise.all([apiRequest<Paged<PositionItem>>('/admin/positions?pageSize=100'), apiRequest<Paged<UnitItem>>('/admin/units?status=ACTIVE&pageSize=100'), apiRequest<Paged<DepartmentItem>>('/admin/departments?status=ACTIVE&pageSize=100')]); items.value = positionList.items; units.value = unitList.items; departments.value = departmentList.items; } catch (e) { error.value = e instanceof Error ? e.message : '加载失败'; } }
function reset() { Object.assign(form, empty()); } function edit(item: PositionItem) { Object.assign(form, item); }
async function save() { busy.value = true; error.value = ''; try { await apiRequest(form.id ? `/admin/positions/${form.id}` : '/admin/positions', { method: form.id ? 'PUT' : 'POST', body: JSON.stringify({ departmentId: form.departmentId, code: form.code, name: form.name, status: form.status, sortOrder: form.sortOrder, ...(form.id ? { version: form.version } : {}) }) }); reset(); await load(); } catch (e) { error.value = e instanceof Error ? e.message : '保存失败'; } finally { busy.value = false; } }
async function remove(item: PositionItem) { if (!confirm(`确认删除岗位“${item.name}”？`)) return; try { await apiRequest(`/admin/positions/${item.id}`, { method: 'DELETE' }); await load(); } catch (e) { error.value = e instanceof Error ? e.message : '删除失败'; } }
onMounted(load);
</script>
<template><section class="page-card"><div class="page-heading"><div><h1>岗位管理</h1><p>岗位归属一个部门，已分配人员的岗位不能删除或跨部门移动。</p></div><button v-if="hasPermission('admin.position.manage')" @click="reset">新建岗位</button></div><div class="filter-toolbar"><label>单位筛选<select v-model="filterUnitId" @change="filterDepartmentId = ''"><option value="">全部单位</option><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.name }}</option></select></label><label>部门筛选<select v-model="filterDepartmentId"><option value="">全部部门</option><option v-for="department in filterDepartments" :key="department.id" :value="department.id">{{ department.name }}</option></select></label></div><div v-if="error" class="form-error">{{ error }}</div><div class="admin-layout"><table class="data-table"><thead><tr><th>单位</th><th>部门</th><th>岗位编码</th><th>岗位名称</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in displayedItems" :key="item.id"><td>{{ item.unitName }}</td><td>{{ item.departmentName }}</td><td>{{ item.code }}</td><td>{{ item.name }}</td><td>{{ item.status === 'ACTIVE' ? '启用' : '停用' }}</td><td><button class="link-button" @click="edit(item)">编辑</button><button v-if="hasPermission('admin.position.manage')" class="link-button danger-text" @click="remove(item)">删除</button></td></tr></tbody></table><form v-if="hasPermission('admin.position.manage')" class="admin-form side-form" @submit.prevent="save"><h2>{{ form.id ? '编辑岗位' : '新建岗位' }}</h2><label>单位<select v-model="form.unitId" required @change="form.departmentId = ''"><option value="">请选择</option><option v-for="unit in units" :key="unit.id" :value="unit.id">{{ unit.name }}</option></select></label><label>部门<select v-model="form.departmentId" required><option value="">请选择</option><option v-for="department in availableDepartments" :key="department.id" :value="department.id">{{ department.name }}</option></select></label><label>岗位编码<input v-model="form.code" required maxlength="64"></label><label>岗位名称<input v-model="form.name" required maxlength="200"></label><label>状态<select v-model="form.status"><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label><label>排序号<input v-model.number="form.sortOrder" type="number" min="0"></label><div class="form-actions"><button type="button" @click="reset">取消</button><button class="primary" :disabled="busy">保存</button></div></form></div></section></template>
