<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { apiRequest } from '../../api';
import { hasPermission } from '../../auth';
import type { Paged, RoleItem } from '../../types';

interface PermissionItem { code: string; name: string; group: string; description: string | null }
const items = ref<RoleItem[]>([]); const permissions = ref<PermissionItem[]>([]); const error = ref(''); const busy = ref(false);
const empty = () => ({ id: '', code: '', name: '', description: '', status: 'ACTIVE', permissionCodes: [] as string[], version: 0, isSystem: false }); const form = reactive(empty());
const groups = computed(() => Array.from(new Set(permissions.value.map(item => item.group))));
async function load() { try { const [roles, points] = await Promise.all([apiRequest<Paged<RoleItem>>('/admin/roles?pageSize=100'), apiRequest<PermissionItem[]>('/admin/permissions')]); items.value = roles.items; permissions.value = points; } catch (e) { error.value = e instanceof Error ? e.message : '加载失败'; } }
function reset() { Object.assign(form, empty()); } function edit(item: RoleItem) { Object.assign(form, { ...item, description: item.description ?? '', permissionCodes: [...item.permissionCodes] }); }
async function save() { busy.value = true; error.value = ''; try { await apiRequest(form.id ? `/admin/roles/${form.id}` : '/admin/roles', { method: form.id ? 'PUT' : 'POST', body: JSON.stringify({ code: form.code.toUpperCase(), name: form.name, description: form.description || null, status: form.status, permissionCodes: form.permissionCodes, ...(form.id ? { version: form.version } : {}) }) }); reset(); await load(); } catch (e) { error.value = e instanceof Error ? e.message : '保存失败'; } finally { busy.value = false; } }
async function remove(item: RoleItem) { if (!confirm(`确认删除角色“${item.name}”？`)) return; try { await apiRequest(`/admin/roles/${item.id}`, { method: 'DELETE' }); await load(); } catch (e) { error.value = e instanceof Error ? e.message : '删除失败'; } }
onMounted(load);
</script>
<template><section class="page-card"><div class="page-heading"><div><h1>角色管理</h1><p>角色权限同时控制菜单和后端接口，系统管理员角色不可修改。</p></div><button v-if="hasPermission('admin.role.manage')" @click="reset">新建角色</button></div><div v-if="error" class="form-error">{{ error }}</div><div class="admin-layout"><table class="data-table"><thead><tr><th>角色编码</th><th>角色名称</th><th>权限数</th><th>状态</th><th>类型</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.code }}</td><td>{{ item.name }}</td><td>{{ item.permissionCodes.length }}</td><td>{{ item.status === 'ACTIVE' ? '启用' : '停用' }}</td><td>{{ item.isSystem ? '系统内置' : '自定义' }}</td><td><button class="link-button" @click="edit(item)">查看</button><button v-if="hasPermission('admin.role.manage') && !item.isSystem" class="link-button danger-text" @click="remove(item)">删除</button></td></tr></tbody></table><form v-if="hasPermission('admin.role.manage')" class="admin-form side-form wide-side-form" @submit.prevent="save"><h2>{{ form.id ? '编辑角色' : '新建角色' }}</h2><label>角色编码<input v-model="form.code" required maxlength="64" :disabled="form.isSystem"></label><label>角色名称<input v-model="form.name" required maxlength="200" :disabled="form.isSystem"></label><label>角色说明<textarea v-model="form.description" maxlength="500" :disabled="form.isSystem"></textarea></label><label>状态<select v-model="form.status" :disabled="form.isSystem"><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></label><div class="permission-groups"><fieldset v-for="group in groups" :key="group"><legend>{{ group }}</legend><label v-for="point in permissions.filter(item => item.group === group)" :key="point.code" class="check-row"><input v-model="form.permissionCodes" type="checkbox" :value="point.code" :disabled="form.isSystem"><span>{{ point.name }}</span></label></fieldset></div><div class="form-actions"><button type="button" @click="reset">取消</button><button v-if="!form.isSystem" class="primary" :disabled="busy">保存</button></div></form></div></section></template>
